name: Regression Tests (argmaxinc/mlx <-> mlexplore/mlx)
run-name: commit-${{ github.sha }}
on:
  workflow_dispatch:
jobs:
  regression-test-mistral:
    name: argmaxinc/mlx=${{ matrix.argmaxinc_mlx_hash }} vs mlxexplore/mlx=${{ matrix.mlxexplore_mlx_hash }}
    runs-on: ${{ matrix.SoC }}
    strategy:
      fail-fast: false
      matrix:
        SoC: [
            "M1", "M2", "M3"
        ]
        argmaxinc_mlx_hash: [
            # "e44480a03d53d9f0895b9f8156ad8c045eb10d4e",
            # "5bf706ad86cbe655f8efb1d5e84316e6efb35593",
            # "92711a8ce5941f2b9ef1b936ca6e4e98a4b3523c",
            "cd6e306b52f2c80eee9662bb225b853796aa48e5",
        ]
        mlxexplore_mlx_hash: [
            # "22364c40b7e488a81c322dfe5663a03daf3190a8",
            "c096a77b9b012a4cc91edcf50683c495a421dcb7",
        ]
        mistral_model: [
            "mlx-community/Mistral-7B-Instruct-v0.2-4-bit",
        ]
    steps:
    - uses: actions/checkout@v4
    - name: argmaxinc/mlx=${{ matrix.argmaxinc_mlx_hash }} vs mlxexplore/mlx=${{ matrix.mlxexplore_mlx_hash }}
      shell: bash -el {0}
      run: |
        conda create -n mlx-bench python=3.11 -y
        conda activate mlx-bench
        pip install -r requirements.txt
        git submodule init && git submodule update
        huggingface-cli login --token ${{ secrets.HF_AO_TOKEN}}
        python bench_mistral.py \
            --repo-a ml-explore/mlx --commit-a ${{ matrix.mlxexplore_mlx_hash }} \
            --repo-b argmaxinc/mlx --commit-b ${{ matrix.argmaxinc_mlx_hash }} \
            --hub-model-name ${{ matrix.mistral_model }} \
            --output-dir external \
            --max-context-length 8100 \
            --fail-for-mismatch-before-n-tokens 8100
