name: Regression Tests
run-name: commit-${{ github.sha }}
on:
  workflow_dispatch:
jobs:
  regression-test-mistral:
    name: ${{ matrix.SoC }} (${{ matrix.commit_a }} vs ${{ matrix.commit_b }})
    runs-on: ${{ matrix.SoC }}
    strategy:
      fail-fast: false
      matrix:
        SoC: [
            "M1-SF", "M2-SF", "M3"
        ]
        commit_a: [
            # "7b463ffb077076e239b8931349d54fd5832b248c"
            "14b4e51a7c6455a61a74d24da9f47dfeb161023f"
        ]
        commit_b: [
            # "0787724c44b870943386fe97ff709ab535f62c9c"
            "14b4e51a7c6455a61a74d24da9f47dfeb161023f"
        ]
        mistral_model: [
            "mlx-community/Mistral-7B-Instruct-v0.2-4-bit",
        ]
        max-context-length: [
          9100,
        ]
        python-version: [
          "3.11",
        ]
    steps:
    - uses: actions/checkout@v4
    - name: Mistral-7b LLM Benchmark (${{ matrix.commit_a }} vs ${{ matrix.commit_b }})
      shell: bash -el {0}
      run: |
        conda create -n mlx-bench python=3.11 -y
        conda activate mlx-bench
        pip install -r requirements.txt
        git submodule init && git submodule update
        huggingface-cli login --token ${{ secrets.HF_AO_TOKEN}}
        python bench_mistral.py \
            --repo-a ml-explore/mlx --commit-a ${{ matrix.commit_a }} \
            --repo-b ml-explore/mlx --commit-b ${{ matrix.commit_b }} \
            --hub-model-name ${{ matrix.mistral_model }} \
            --output-dir external \
            --max-context-length ${{ matrix.max-context-length }} \
            --fail-for-mismatch-before-n-tokens ${{ matrix.max-context-length }}
